import { Plus_Jakarta_Sans } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

const PJS = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Dimas Prihady S.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>

      <body className={PJS.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
